select * from customers;

--what is the total revenue generated by male vs female customers?

select gender,
sum(purchase_amount) as total_revenue
from customers
group by gender;

--which customers used a discount but still spent more than the average purchase amount?

select distinct customer_id
from customers
where discount_applied='Yes'
and
purchase_amount>(select avg(purchase_amount) from customers);

--which are the top 5 products with the highest average review rating?

select item_purchased as products,
avg(review_rating) as average_rating
from customers
group by item_purchased
order by average_rating desc
limit 5;

--compare the average purchase amounts between standard and express shipping

select shipping_type,
avg(purchase_amount)
from customers 
where shipping_type='Standard' or shipping_type='Express'
group by shipping_type;

--do subscribed customers spend more?compare average spend and total revenue between subscribers and non subscribers

select 
case
when subscription_status='Yes' then 'Subscribers'
else 'Non subscribers'
end as customer_type,
avg(purchase_amount) as average_purchase_amount,
sum(purchase_amount) as total_revenue
from customers
group by subscription_status;

--which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased as product,
round(
      sum(
           case
		   when discount_applied='Yes' then 1
		   else 0
		   end
  )*100/count(*),2
) as discount_percentage
from customers 
group by item_purchased
order by discount_percentage desc
limit 5;

--segment customers into loyal,returning and new based on their no of previous purchases and show the count of each segment

select 
case when previous_purchases=0  then  'new'
when previous_purchases between 1 and 10 then 'returning'
else 'loyal'
end as customer_segment,
count(*) as customer_count
from customers
group by customer_segment;

--what are the top 3 purchased products within each category?

select category, product, purchase_count
from (
    select category,
           item_purchased as product,
           count(*) as purchase_count,
           row_number() over (
               partition by category
               order by count(*) desc
           ) as rn
    from customers
    group by category, item_purchased
) t
where rn <= 3;

--are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?

select
    case
        when previous_purchases > 5 then 'repeat_buyer'
        else 'non_repeat_buyer'
    end as customer_type,
    count(*) as total_customers,
    sum(case when subscription_status = 'Yes' then 1 else 0 end) as subscribers,
    round(
        (sum(case when subscription_status = 'Yes' then 1 else 0 end) * 100.0
        / count(*))::numeric,
        2
    ) as subscription_rate
from customers
group by
    case
        when previous_purchases > 5 then 'repeat_buyer'
        else 'non_repeat_buyer'
    end;
	
--what is the revenue contribution of each age group?

select
    case
        when age between 18 and 25 then '18-25'
        when age between 26 and 35 then '26-35'
        when age between 36 and 45 then '36-45'
        else '46+'
    end as age_group,
    sum(purchase_amount) as revenue,
    round(
        (sum(purchase_amount) * 100.0 /
        (select sum(purchase_amount) from customers))::numeric,
        2
    ) as revenue_percentage
from customers
group by
    case
        when age between 18 and 25 then '18-25'
        when age between 26 and 35 then '26-35'
        when age between 36 and 45 then '36-45'
        else '46+'
    end
order by revenue desc;
